codecov:
  max_report_age: 24h

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        threshold: 2%
    patch:
      default:
        threshold: 2%
    changes:
      default:
        threshold: 2%