name: CD-Examples

on:
  push:
    branches: [ develop-examples-app ]

jobs:
  deploy-to-github-pages:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
      
    - name: Install .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.301
    
    - name: Build & test
      run: dotnet test src/TypinExamples/TypinExamples.sln --configuration Release #--logger 
      
    - name: Publish .NET Core Project
      run: dotnet publish src/TypinExamples/TypinExamples.sln --configuration Release -o release --nologo
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
