name: CI-Example

on:
  push:
    branches:
      - devlop-examples-app
    tags-ignore:
      - '*'
    paths-ignore:
      - 'src/TypinExamples/*'
      - LICENSE
      - 'CHANGELOG.md'
      - 'README.md'
  pull_request:
    branches-ignore:
      - 'develop'
    tags-ignore:
      - '*'
    paths-ignore:
      - 'src/Typin/*'
      - LICENSE
      - 'CHANGELOG.md'
      - 'README.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100

    - name: Build & test
      run: dotnet test src/TypinExamples/TypinExamples.sln --configuration Release #--logger GitHubActions

    - name: Upload coverage
      uses: codecov/codecov-action@v1.0.14
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./src/TypinExamples/Examples/TypinExamples.HelloWorld.Tests/bin/Release/Coverage.xml,
               ./src/TypinExamples/Examples/TypinExamples.CalculatOR.Tests/bin/Release/Coverage.xml,
               ./src/TypinExamples/Examples/TypinExamples.Timer.Tests/bin/Release/Coverage.xml,
               ./src/TypinExamples/Examples/TypinExamples.InteractiveQuery.Tests/bin/Release/Coverage.xml,
               ./src/TypinExamples/Examples/TypinExamples.MarioBuilder.Tests/bin/Release/Coverage.xml
