name: CI-Examples

on:
  push:
    branches:
      - develop-examples-app
    tags-ignore:
      - '*'
    paths:
      - 'src/TypinExamples/*'
  pull_request:
    branches:
      - '*'
    tags-ignore:
      - '*'
    paths:
      - 'src/TypinExamples/*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1.403

    - name: Build & test
      run: dotnet test src/TypinExamples/TypinExamples.sln --configuration Release --logger GitHubActions

#    - name: Upload coverage
#      uses: codecov/codecov-action@v1.0.5
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        file: src/Typin/Typin.Tests/bin/Release/Coverage.xml
#
#    - name: Upload coverage (analyzers)
#      uses: codecov/codecov-action@v1.0.5
#      with:
#        token: ${{ secrets.CODECOV_TOKEN }}
#        file: src/Typin/Typin.Analyzers.Tests/bin/Release/Coverage.xml
